-- Create users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    role VARCHAR2(10) NOT NULL,
    balance NUMBER(10,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_username_unique UNIQUE (username),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('admin', 'customer'))
);

-- Create cars table
CREATE TABLE cars (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR2(50) NOT NULL,
    model VARCHAR2(50) NOT NULL,
    year NUMBER NOT NULL,
    color VARCHAR2(30) NOT NULL,
    price_per_day NUMBER(10,2) NOT NULL,
    available NUMBER(1) DEFAULT 1 CHECK (available IN (0,1)),
    image_path VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create rentals table
CREATE TABLE rentals (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    car_id NUMBER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_price NUMBER(10,2) NOT NULL,
    status VARCHAR2(10) DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rentals_user_fk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT rentals_car_fk FOREIGN KEY (car_id) REFERENCES cars(id)
);

-- Insert sample admin user
INSERT INTO users (username, password, email, role) 
VALUES ('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin@example.com', 'admin');

COMMIT;
